### ISSUE TITLE
Flickering line gone after switching renderers

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1269]
Boot to BASIC on a European MSX2, e.g. 8250 at WIDTH 37 (default).
Then (as PGimeno wrote): 
- when I enter: `vdp(10)=130`, there's a line flickering; later when I enter: `vdp(10)=2`, there's a line that shouldn't be there
- when I change to another renderer, that line goes
- but if I repeat, the line is back no matter the renderer

I don't think such effects should be influenced by renderer switches.

Anyway, on a real 8250, the line isn't visible at all, he writes:  the last line I see is the one with the centre line of the numbers 9, 8 and 6 (which are partially visible at the bottom right). There's no flickering line or anything else below.

This is what it looks like on real hardware:

![VDP10_130](https://user-images.githubusercontent.com/12675978/83977628-35735100-a902-11ea-8d90-e3be68c76cd3.jpg)

This is openMSX in the same situation, the bottom pixelline is flickering.
![openmsx2567](https://user-images.githubusercontent.com/12675978/83977642-59cf2d80-a902-11ea-827c-75be2fcbc2f6.png)

When doing VDP(10)=2 again, the flickering line remains and on real MSX all looks normal.

**Comment by m9710797** [comment]
I somehow missed this bug report (I did see it, didn't have time immediately, but then forgot about it). Sorry.

The problem already occurs in the first part of the first step in the problem description: there shouldn't be any "flickering" line after "VDP(10)=130". The garbage characters at the bottom are normal, but it should not change from frame to frame.

But I can't reproduce it. Might this have been fixed in the mean time?
@PGimeno: can you specify in detail what video settings you use? (scale factor/algorithm, noise, blur, scanline, horizontal-stretch, ...)
Can anyone else (still) reproduce this?

**Comment by MBilderbeek** [comment]
Yes, I can still see the flickering line when doing that out.

**Comment by m9710797** [comment]
OK, now that I know how to reproduce it. I think I was able to fix it.
Can you verify? Thanks.

**Comment by MBilderbeek** [comment]
Fixed indeed with 6f50b84788ffe4642ba8b5e783faf45546a39131 Thanks!
