### ISSUE TITLE
Default light theme improvement suggestions. Was: imgui light has unreadable white on white text color.

### ISSUE THREAD

**Issue by gilbertfrancois** [openMSX/openMSX#1567]
When choosing imgui light style, some texts in the menus, message log console, symbol manager dialog and more are unreadable, due to showing white text on white background. Moreover, some UI elements look strange too, compared to the dark style.

See screenshots for comparison:

<img width="1470" alt="Screenshot 2023-12-04 at 13 08 16" src="https://github.com/openMSX/openMSX/assets/15607023/93c83595-d5af-4870-9673-1c5468a64ec2">

<img width="1470" alt="Screenshot 2023-12-04 at 13 13 40" src="https://github.com/openMSX/openMSX/assets/15607023/666009ad-c7ef-4669-b720-295288785371">

**Comment by m9710797** [comment]
Oops, the style selector changes the colors of all builtin ImGui widgets. But we didn't go back and adjust all (currently hardcoded) color values that openMSX itself picks.

Give me a few days. I'll try to change those colors so that they also change according to the selected style.

**Comment by m9710797** [comment]
See above commit message.
Most things are solved already, but maybe not everything.
Please test and report all things I overlooked.
And the colors for the syntax highlighting in the console could need some fine-tuning. Any volunteers for that?

**Comment by gilbertfrancois** [comment]
Is there a imgui config file somewhere hidden in the home folder? I have compiled 5a8c46b2c2d31659e742e50e9fc3e9080f7f1764 but the only change I see is a light yellow font in the console log terminal, instead of white. The menus and symbol manager look still the same. I deleted the `~/.openmsx` but that did not resolve the issue. I also searched in `~/.local`, `~/.cache` and `~/Library`, but no luck so far.

**Comment by m9710797** [comment]
Oops, you're right.
I searched through our code for all hardcoded colors encoded as a 32-bit hex value (rrggbbaa). But I missed the places where colors are encoded as a tuple of 4 floats.
So indeed, the symbol manager and the message log still use hardcoded colors. I'll try to fix this soon (but maybe not today).

Though note that in your style=light screenshot, the menu does look correct. I agree it's not pretty, but that is how the default Dear ImGui light style looks in menus.

**Comment by m9710797** [comment]
@gilbertfrancois Can you try again?

**Comment by gilbertfrancois** [comment]
It looks really good. I could not find places where the font has the same color as the background. To improve the usability in the menus, I have the following suggestions. All colors standard from the imgui light theme, except:


Option 1:
```
FrameBorder  true
WindowBg     255,255,255,255
```

<img width="1470" alt="var0" src="https://github.com/openMSX/openMSX/assets/15607023/ab77afd0-5843-446b-a325-d067381d3730">


---
Option 2:
```
WindowBg     255,255,255,255
FrameBg      240,240,240,255
```

<img width="1470" alt="var1" src="https://github.com/openMSX/openMSX/assets/15607023/6d5a268f-dbbe-4a47-ae25-2104223a35ef">

----
Option 3
```
PopupBg      245,245,245,255
```

<img width="1470" alt="var2" src="https://github.com/openMSX/openMSX/assets/15607023/4e9e08ea-33b2-46bc-8f6a-10362d689ba1">


I have a strong preference for option 1, where the window and menu background is pure white with frame borders. This is most close to the native colour scheme of macOS and Windows light theme. The gray background looks a bit from the past, like in  Windows 95/98/2000.

If you're interested, I can tune the blues also more to the native L&F of e.g. Windows 11 and macOS. Just let me know...

**Comment by m9710797** [comment]
Hi gilbertfrancois,

I'm not against deviating from the default Dear ImGui light style. But before doing that, please test your proposed changes also with the "Dear ImGui Demo" window.  In openMSX go to "Settings > Advanced > ImGui Demo Window" (all the way at the bottom). This demo shows most (all?) of the Dear ImGui widgets in various contexts. So including stuff we might use in the next openMSX window.

Wouter

**Comment by MBilderbeek** [comment]
@gilbertfrancois any conclusions?

**Comment by MBilderbeek** [comment]
@ocornut Would the suggestions from https://github.com/openMSX/openMSX/issues/1567#issuecomment-1841658833 be useful to include upstream as improvements to the Light theme defaults?

**Comment by ocornut** [comment]
Feel free to tweak them locally, it won't hurt, and I am happy to see your progress.

I think those colors were originally inspired by some OSX version which probably had this this way (greyer windows, brighter frames/popups). I agree it should be improved, for now I'm trying to avoid tweaking those styles too much, as I would rather work on styling v2 system. The style system is currently too limited.

**Comment by MBilderbeek** [comment]
@m9710797 what's the best way to tweak such a standard ImGuiColor entry that belongs to a certain style?  I guess we shouldn't change the imgui code for this :)

**Comment by MBilderbeek** [comment]
Brazza on MRC wrote:

> Another problem(not really a problem Wink ) I found was the color contrast in some windows (Light Style), but I'm not sure if this problem happens to everyone. If it's just on my computer, then it's already fixed with the changes I made.
I solved this by changing the file: imgui_draw.cc
More details in the attached image (The window in the screenshot is just an example, the problem happens in other windows as well).
> ![image](https://github.com/user-attachments/assets/fe059cdc-8533-4d9d-a96e-7d0311a5659d)

When I take a look, I see something similar:

![image](https://github.com/user-attachments/assets/6444a968-e511-4c92-8eb3-157763b360ce)

But in other windows it's different:
![image](https://github.com/user-attachments/assets/f3dd5c76-48ba-420b-9b69-c513037355f9)

So, what is going on here? Looks like the background of windows is darker than in menus?
