### ISSUE TITLE
[Bug] Sex Bomb Bunny vertically shaking image at certain vertical adjust values [sf#170]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#471]
**Reported by manuelbi on 2004-11-21 18:50 UTC**
In Sex Bomb Bunny the whole screen shakes during the
game if the vertical set adjust is -7, -6, -5, -4, -3,
-2, 6, 7 or 8.
AFAIK the game uses overscan, so it could be related to
that.
Ark-A-Noah doesn't have the problem, though, and that
game definately uses overscan.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2005-07-24 16:11 UTC**
Logged In: YES 
user_id=78178

Some additional info: the total amplitude of the shaking is
20 pixels on the SDL screen. The graphics when it's in the
lowest position reach up to line 475 on the SDL window!

Note that this doesn't happen on a real MSX.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2005-10-29 19:22 UTC**
Logged In: YES 
user_id=78178

Unknown Reality also experiences this kind of problems in
the Scope part, during subparts "zoomer", "blue blockers"
(the twisting bars) and "Jelly Waves" (the green and red
vertical bars).
What we see there is that every other frame the wrong page
is displayed. 

In SBB the shaking effect is actually the fact that every
other frame a vertically shifted version of the page is
shown. I don't know if this is coming from another page or not.

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2005-10-29 19:22 UTC**
- **summary**: Sex Bomb Bunny screen shakes at certain set adjust values --> Sex Bomb Bunny an UR bugs at certain vertical adjust values

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2008-05-25 14:39 UTC**
Logged In: YES 
user_id=78178
Originator: YES

The problem also manifests itself in the intro of the MCFN music disk Jarretenk.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2008-05-25 15:02 UTC**
Logged In: YES 
user_id=78178
Originator: YES

Please scratch out that last comment. That disk behaves wrong when it starts on a machine which has not SCREEN 0.80 set in basic, which also happens on a real MSX.

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2014-09-15 21:08 UTC**
- **status**: open --> closed-fixed
- **Group**:  --> Next_release

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2014-09-15 21:08 UTC**
I don't know how or when, but this bug seems to be fixed. I can't reproduce it anymore (tried a 8245 with set adjust (-7,-7) with SBB and UR (using extra RAM).

**Comment by MBilderbeek** [comment]
After a trigger from David/Wouter I tried again, and I could reproduce it with SBB again, but not with UR, in a very quick test.

**Comment by sdsnatcher** [comment]
Sex Bomb Bunny flickers constantly and it's unplayable.

Tested on openMSX-0.14.0 on Mac OS-X 10.11.6.

EDIT: BTW, tested with SETADJUST = 0,0 and 1,1.

**Comment by sdsnatcher** [comment]
Here's [a video I recorded that shows how much Sex Bomb Bunny flickers in openMSX-0.14.0](https://www.youtube.com/watch?v=5oP1ClYidiQ), making it unplayable. The video **must be watched at 720p 60Hz**, otherwise the Youtube player will just skip half of the frames and the problem won't be shown.

**Comment by grauw** [comment]
With the default adjust (0, 0), Sex Bomb Bunny uses a vertical adjust of -6 (r#19 is 96). It sets line interrupts on line 200 and 230.

**Comment by Colpocorto** [comment]
SBB still shaking the screen on OpenMSX 19.0

**Comment by MBilderbeek** [comment]
That's correct, no update on this issue. (Also none reported here.)

I can reproduce with the following set-adjust values (Y): -1, 0, 1, 2, 3, 4 and 5.

A workaround is therefore, to use vertical adjust of: -7, -6, -5, -4, -3, -2, 6, 7.

@grauw are you interested to help debugging this weird issue?

**Comment by MBilderbeek** [comment]
[sbb.dsk.gz](https://github.com/user-attachments/files/18669846/sbb.dsk.gz)

**Comment by Colpocorto** [comment]
> [sbb.dsk.gz](https://github.com/user-attachments/files/18669846/sbb.dsk.gz)

has the bug been fixed at last?

**Comment by MBilderbeek** [comment]
What makes you think so? I just added the disk image for easy testing...

**Comment by Colpocorto** [comment]
Ah, sorry. Seeing the "bug" label removed made me think so.

**Comment by MBilderbeek** [comment]
Unfortunately, it is still not known at all what the cause of this is.

Anyway, if it would have been 'closed' you would have a point! 
I've been going through all issues as there is now an issue type, and one is "Bug", so I removed all bug labels and replaced it with the issue type.
